// pkgs/web/src/QuickSettings.tsx
import { type Accessor, For, useContext } from "solid-js";
import { version } from "../package.json";
import { ThemePicker } from "./components/ThemePicker";
import { IntlCtx, locales, locale, setLocale } from "./i18n";

type DropdownProps = {
	children?: any;
	icon: string;
	label: Accessor<string>;
	href: string;
};
function DropdownItem(props: DropdownProps) {
	return (
		<li class="grid grid-cols-subgrid col-span-2 hover:bg-fg/10 pe-4">
			<a href={props.href} class="flex p-4 gap-2 items-center">
				<span class={props.icon} />
				<span>{props.label()}</span>
			</a>
			{props.children}
		</li>
	);
}

export function QuickSettings() {
	const t = useContext(IntlCtx);

	return (
		<ul class="grid grid-cols-[minmax(0,1fr)_1fr] w-86 select-none my-4">
			<DropdownItem
				icon="icon-[mingcute--paint-brush-line] scale-x-[-1]"
				href="/settings/theme"
				label={t("Theme")}
			>
				<ThemePicker />
			</DropdownItem>
			<DropdownItem
				icon="icon-[mingcute--font-size-line]"
				href="/settings/theme"
				label={t("Font size")}
			>
				<input
					name="fontSize"
					class="w-42"
					type="range"
					min={8}
					max={48}
					value="20"
					onChange={(ev) =>
						document.documentElement.style.setProperty(
							"--font-size",
							`${ev.target.value}px`,
						)
					}
				/>
			</DropdownItem>
			<DropdownItem
				icon="icon-[mingcute--globe-line]"
				href="/settings#language"
				label={t("Language")}
			>
				<select
					name="language"
					class="ps-2"
					value={locale()}
					onChange={(ev) => setLocale(ev.target.value)}
				>
					<For each={locales}>
						{(o) => (
							<option value={o}>
								{new Intl.DisplayNames(o, { type: "language" }).of(o)}
							</option>
						)}
					</For>
				</select>
			</DropdownItem>
			<DropdownItem
				icon="icon-[mingcute--settings-5-line]"
				href="/settings"
				label={t("Settings")}
			>
				<a href="/settings" class="content-center text-end">
					v{version}
				</a>
			</DropdownItem>
		</ul>
	);
}

// web/src/components/QuickSettings.svelte
<script lang="ts">
import { settings, themes } from "../settings.svelte";
import { t } from "../l10n.svelte.ts";
import { p, route } from "../routes.ts";
import Select from "./Select.svelte";
</script>

<form class="table">
	<!-- <label> -->
	<!-- 	<span>{t("Language")}</span> -->
	<!-- 	<Select name="locale" bind:value={settings.locale}> -->
	<!-- 		{#each locales as k} -->
	<!-- 			<option value={k}> -->
	<!-- 				{new Intl.DisplayNames([k], { type: "language" }).of(k)} -->
	<!-- 			</option> -->
	<!-- 		{/each} -->
	<!-- 	</Select> -->
	<!-- </label> -->
	<label>
		<span>{t("Theme")}</span>
		<Select name="theme" bind:value={settings.theme}>
			{#each themes as theme}
				<option value={theme}>{t(theme)}</option>
			{/each}
		</Select>
	</label>
	<label>
		<span>{t("Font size")}</span>
		<div>
			{settings.fontSize}
			<input
				type="range"
				min="8"
				max="48"
				step="2"
				bind:value={settings.fontSize}
			/>
		</div>
	</label>
	<label>
		<span>{t("Line height")}</span>
		<div>
			{settings.lineHeight}
			<input
				type="range"
				min="1"
				max="2"
				step="0.1"
				bind:value={settings.lineHeight}
			/>
		</div>
	</label>
	<a href={p("/settings")}>
		<span>{t("Settings")}</span>
		<span>v{APP_VERSION}</span>
	</a>
</form>

<style>
form {
	padding: --spacing(2) 0;
	width: --spacing(84);
	--select-bg: var(--color-bg-300);
}
:global(#popover) {
	position: absolute;
	display: none;
	background: var(--color-bg-200);
	filter: drop-shadow(var(--drop-shadow-xl));
	border-radius: var(--radius-md);
}
</style>
